on:
  workflow_call:
    secrets:
      KUBECONFIG:
        required: true

jobs:
  deploy:
    name: Production Pipeline ðŸš€
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: socialgouv/workflows/actions/deployment-starting@v1
        id: deployment-starting
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          environment-scope: production

      - uses: socialgouv/kontinuous/.github/actions/deploy-via-github@v1
        continue-on-error: true
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          kubeconfig: ${{ secrets.KUBECONFIG }}
          environment: prod
      
      - uses: socialgouv/workflows/actions/deployment-ending@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          deployment-id: ${{ steps.deployment-starting.outputs.deployment-id }}
          deployment-name: ${{ steps.deployment-starting.outputs.deployment-name }}